In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from ucimlrepo import fetch_ucirepo 

# Fetch dataset
heart_disease = fetch_ucirepo(id=45)
print("Raw features data:", heart_disease.data.features[:5]) 

Raw features data:    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  
0  0.0   6.0  
1  3.0   3.0  
2  2.0   7.0  
3  0.0   3.0  
4  0.0   3.0  


In [9]:
#1(5 pts) Clean your dataset to turn categorical values into numerical ones. One-hot encoding is likely the answer, but it depends on the dataset. Your data may have ordinal columns, for example where one-hot encoding is not as appropriate.
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from ucimlrepo import fetch_ucirepo 

heart_disease = fetch_ucirepo(id=45)
X = pd.DataFrame(heart_disease.data.features, columns=heart_disease.data.feature_names)
y = pd.Series(heart_disease.data.targets.squeeze(), name='Outcome')
class_labels = LabelEncoder()
columns = ['sex','cp','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
#USED MEDIUM.COM
heartdisease_hot = pd.get_dummies(X[columns])
heartdisease_hot

sex  cp  chol  fbs  restecg  thalach  exang  oldpeak  slope   ca  thal
0      1   1   233    1        2      150      0      2.3      3  0.0   6.0
1      1   4   286    0        2      108      1      1.5      2  3.0   3.0
2      1   4   229    0        2      129      1      2.6      2  2.0   7.0
3      1   3   250    0        0      187      0      3.5      3  0.0   3.0
4      0   2   204    0        2      172      0      1.4      1  0.0   3.0
..   ...  ..   ...  ...      ...      ...    ...      ...    ...  ...   ...
298    1   1   264    0        0      132      0      1.2      2  0.0   7.0
299    1   4   193    1        0      141      0      3.4      2  2.0   7.0
300    1   4   131    0        0      115      1      1.2      2  1.0   7.0
301    0   2   236    0        2      174      0      0.0      2  1.0   3.0
302    1   3   175    0        0      173      0      0.0      1  NaN   3.0

[303 rows x 11 columns]

In [16]:
#2(3 pts) Perform univariate linear regression on the dataset. Select your variable to predict. How well did this model perform? Is this a good approach for this dataset? Why or why not? 
import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
heartdisease_hot = heartdisease_hot[['sex','cp','chol','fbs','restecg', 'exang','oldpeak','slope','ca']].dropna()
#Redefining X and Y
X = np.array(heartdisease_hot['sex']).reshape(-1,1)
y = np.array(heartdisease_hot['chol']).reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
regression_model = LinearRegression()
regression_model.fit(X_train, y_train)
y_pred = regression_model.predict(X_test)
y_pred
accuracy_score = regression_model.score(X_test, y_test)
print(accuracy_score)
#The model did not perform well, and now this was not a good approach because the values aren't just 1 and 0 and therefore this is a innapropriate model for this type of data.

0.02960914256257763


In [20]:
#3(8 pts) Perform KNN on this dataset. As part of this, write a function that selects the optimal value of k. How well did this model perform?
#The model performed not too badly because it was 0.73 a lot better than 0.02 and is significant.
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import pandas as pd
from ucimlrepo import fetch_ucirepo
heart_disease = fetch_ucirepo(id=45)
X = heartdisease_hot.drop(['sex'], axis = 1)
y = heartdisease_hot['sex']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train) 
X_test = sc.fit_transform(X_test)
knn = KNeighborsClassifier(n_neighbors=15) 
knn.fit(X_train, y_train) 
y_pred = knn.predict(X_test)
print(y_pred)
print(type(y_pred))
print(knn.score(X_test, y_test))

[1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0
 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1]
<class 'numpy.ndarray'>
0.7333333333333333


In [24]:
#4(6 pts) Work with your dataset to perform logistic regression. How well did this perform?
#It has a 69% value so I don't think it means very good nor very bad, so slightly statistically significant.
from ucimlrepo import fetch_ucirepo
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
acc_train=[]
acc_test=[]

neighbors=range(1,50)

for neighbor in neighbors:
    KNN=KNeighborsClassifier(n_neighbors=neighbor)
    KNN.fit(X_train,y_train)
    acc_train.append(KNN.score(X_train,y_train))
    acc_test.append(KNN.score(X_test,y_test))
mean_accuracy = sum(acc_test) / len(acc_test)
print("Mean accuracy:", mean_accuracy)
   


Mean accuracy: 0.6943310657596372


In [26]:
#5. (3 pts) Perform normalization on your dataset. Does it change the performance for 2-4? What is the best measure of performance for your dataset (accuracy or something else) and why?
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import pandas as pd
from ucimlrepo import fetch_ucirepo
heart_disease = fetch_ucirepo(id=45)
X = pd.DataFrame(heart_disease.data.features, columns=heart_disease.data.feature_names)
y = heart_disease.data.targets.squeeze()
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42, stratify=y)
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)
def train_and_evaluate_model(X_train, X_test, y_train, y_test):
    model = LogisticRegression(random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    confusion = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred, zero_division=1)
    print("Accuracy with normalization:", accuracy)
    print("Confusion Matrix (normalized):\n", confusion)
    print("Classification Report (normalized):\n", report)
train_and_evaluate_model(X_train_normalized, X_test_normalized, y_train, y_test)


#Yes the performance does change with different classes. The f1-score changes with different classifications because the data that comes from classification can vary, 
#each class doesn't have the same data size.Also there can be false negatives's and positives. It's one of the biggest issues with classification reports,
#but that is why we used normalization to eliminate that. The F1 score is the gold standard for performance/accuracy. All code was adapted from Joel grus network analysis and I used codes for geeks for the squeeze. 


Accuracy with normalization: 0.6065573770491803
Confusion Matrix (normalized):
 [[31  1  1  0  0]
 [ 6  4  1  0  0]
 [ 2  1  0  4  0]
 [ 0  1  4  2  0]
 [ 0  2  0  1  0]]
Classification Report (normalized):
               precision    recall  f1-score   support

           0       0.79      0.94      0.86        33
           1       0.44      0.36      0.40        11
           2       0.00      0.00      0.00         7
           3       0.29      0.29      0.29         7
           4       1.00      0.00      0.00         3

    accuracy                           0.61        61
   macro avg       0.51      0.32      0.31        61
weighted avg       0.59      0.61      0.57        61

