In [4]:
%pip install pandas
import pandas as pd

Note: you may need to restart the kernel to use updated packages.


In [7]:
import pandas as pd
csv_df=pd.read_csv('cars.csv', delimiter=";")
csv_df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

In [10]:
import numpy as np
a = np.array ([[1,2,3],[4,5,5,]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)
#2 dimensions here , 2x3 , much faster than python lists, can only combine arrays of the same hape

2 (2, 3) float32


In [16]:
import numpy as np
b = np.array ([[[2,4,6],[8,10,12],[14,16,18]]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

3 (1, 3, 3) float32


In [18]:
c = np.array ([[[2,4,6],[8,10,12],[14,16,18]]], ndmin= 6)
c

array([[[[[[ 2,  4,  6],
           [ 8, 10, 12],
           [14, 16, 18]]]]]])

In [19]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
a = np.array([1,2,3,4,5,6,])
a

array([1, 2, 3, 4, 5, 6])

In [24]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [27]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
b = b.T
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [29]:
b = b.transpose((1,0))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])